create database	ASSIGNMENT_6
USE ASSIGNMENT_6

-- Q CREATE A VIEW EMPSALDETAILS TO  GET EID NAME DOJ DEPT DESI SALARY AS BASIC ALSO CALCULATE HRA (15% OF BASIC ) PF (9% OF BASIC) NET (BASIC +HRA+PF)

-- SOLUTION 

SELECT * FROM EMP
SELECT * FROM EMP_SAL

CREATE VIEW EMP_SAL_DETAILS
AS 
SELECT E1.EID,NAME, DOJ,DEPT,DESI,SALARY AS 'BASIC', SALARY*0.15 AS 'HRA',SALARY*0.09 AS 'PF',SALARY+SALARY*0.09+SALARY*0.15 AS 'NET' FROM EMP E1
INNER JOIN EMP_SAL E2
ON E1.EID=E2.EID


SELECT * FROM EMP_SAL_DETAILS
WHERE DEPT = 'OPS'


-- QUESTION 2  CREATE A VIEW TOP DISPLAY EID NAME DOJ DESI DEPT OF ALL THE MANAGERS JOINED IN 2019

--SOLUTION 1 USING THE PREVIOUS VIEW WE CREATED 

SELECT EID,NAME ,DOJ,DESI,DEPT FROM EMP_SAL_DETAILS
WHERE DESI='MANAGER' AND DOJ LIKE '%2019%'
SELECT YEAR(DOJ) FROM EMP_SAL_DETAILS


--SOLUTION 2
CREATE VIEW MANAGER2019
AS 
SELECT E1.EID,NAME, DOJ,DESI,DEPT FROM EMP E1
INNER JOIN EMP_SAL E2
ON E1.EID=E2.EID
WHERE DESI='MANAGER' AND YEAR(DOJ)=2019; -- DONT USE DOJ='2019' THIS IS STRING TYPE WHERE AS WE HAVE DATE TYPE



SELECT * FROM MANAGER2019;

--- Q3 CREATE  A VIEW TO HOWMANY TEAM MEMBERS ARE THERE IN EACH DEPARTMENT , IN EACH CITY  ALONG WITH THE TOTAL AND AVERAGE SALARY 


 CREATE VIEW CLASSIFICATIONN
 AS 
 SELECT DEPT,E1.CITY, COUNT(E1.EID) AS 'TOTAL MEMBERS',SUM(SALARY) AS 'TOTAL SALARY',AVG(SALARY) AS 'AVG SAL' FROM EMP_SAL E2
 INNER JOIN EMP E1
 ON E1.EID=E2.EID
 GROUP BY CITY,DEPT












