CREATE DATABASE ASSIGNMENT5;
USE ASSIGNMENT5

SELECT * FROM EMP

SELECT * FROM EMP_SAL

--Q IN THE EMP TABLE DISPLAY    EID , NAME CITY DOJ,DEPT,DESI,SALARY OF THE DELHI EMPLOYEES

SELECT E1.EID,NAME,CITY,DOJ,DEPT,DESI,SALARY FROM EMP E1 
INNER JOIN EMP_SAL E2
ON E1.EID=E2.EID
WHERE CITY='DELHI'
  

-- Q 2 DETAILS OF ALL EMPLOYEES WHOSE SALARY DETAILS ARE NOT AVILABLE 

SELECT * FROM EMP_SAL
WHERE SALARY=NULL


SELECT E1.EID,NAME,CITY,DOJ,DEPT,DESI,SALARY FROM EMP E1 
FULL JOIN EMP_SAL E2
ON E1.EID=E2.EID
--WHERE SALARY = NULL THIS WONT WORK
WHERE SALARY IS NULL
 
 --- 

