CREATE DATABASE ASSIGNMENT1;
USE ASSIGNMENT1;

CREATE TABLE EMP
(
EID CHAR(6),
NAME VARCHAR(16),
ADRESS_CITY VARCHAR(10),
DOB DATE,
PHONE CHAR(10),
EMAIL VARCHAR(25)
);


INSERT INTO EMP
VALUES('E00001','ARJUN','BENGALURU','1.20.2000','9090909088','ULALA@GMAIL.COM');
SELECT * FROM EMP;
INSERT INTO EMP
VALUES('E00002','BRJUN','BENGALURU','1.2.2000','9090909088','ULAAALA@GMAIL.COM');
SELECT * FROM EMP;
INSERT INTO EMP
VALUES('E00003','BRJ','BENGAL','1.2.2090','9090909086','UHHHAAALA@GMAIL.COM');
INSERT INTO EMP
VALUES('E00006','JHSBBB','KOLKATAL','1-2-2090','9090979086','HHHAAALA@GMAIL.COM');
SELECT * FROM EMP; --ASSIGNMENT TABLE 
SELECT * FROM EMPP;--IMPORTED TABLE 

--WORKING WITH IMPORTED TABLE 

--SQL CLAUSE

--  1. WHERE CLAUSE : WORKS AS A FILTER
--EXMP 1
SELECT * FROM EMPP WHERE CITY='DELHI';
 
 --EXMP 2
  SELECT * FROM EMPP 
  WHERE EID=1003;


  SELECT NAME FROM EMPP WHERE CITY='DELHI';

  --LIKE CLAUSE 
-- PERCENT SINGN CLAUSE
SELECT * FROM EMPP
WHERE NAME LIKE '%GUPTA';

SELECT * FROM EMPP
WHERE NAME LIKE 'Y%';

SELECT *FROM EMPP 
WHERE ADDR2 LIKE '%DWARKA%'

--(_) UNDERSCORE , FETCHING FIXED AMOUNT O LETTER/CHARACTERS

SELECT * FROM EMPP
WHERE NAME LIKE '_____';

--Q -FETCH NAME STARTING WITH R AND ONLY 5 CHARACTER INCLUDING R

SELECT * FROM  EMPP
WHERE NAME LIKE 'R____'
--NO RECORDS 
--LETS USE ASSIGNMENT TABLE ADD THE NAME AND TRY TO FETCH 

INSERT INTO EMP(NAME)
VALUES('ROHAN');

SELECT * FROM EMP
WHERE NAME LIKE 'R____'
--SUCESSFUL

--TOP CLAUSE
SELECT TOP 2 NAME FROM EMP;


--DELETE , DROP,TRUNCATE

--ALTER (DDL)
-- TOO ADD AND DELETE COLUMN
 
 ALTER TABLE EMP
 ADD  HAHAHCOLUMN_NAME TEXT;
 SELECT * FROM EMP

 --DELETE COLUMN
 ALTER TABLE EMP
 DROP COLUMN HAHAHCOLUMN_NAME;

 --CHANGE THE DATA TYPE OF COLUMN

 ALTER TABLE EMP
  ALTER COLUMN PHONE TEXT;


  -- SQL OPERATORS 

  --SQL CONSTRAINTS

  --1 NOT NULL

  CREATE TABLE CONSTRAINTTS
  (
 NAME CHAR(8) NOT NULL,
 AGE INT
  )
  INSERT INTO CONSTRAINTTS(AGE)
  VALUES(12);
  --THIS WONT ALLOW BCZ NOT NULL WONT LET NAME HAVE ANY NULL VALUES

  INSERT INTO CONSTRAINTTS
  VALUES('HHAA',0)
  SELECT * FROM CONSTRAINTTS

--TO ADD NOT NULL CONSTRAINT TO ALREADY CREATED TABLE

ALTER TABLE CONSTRAINTTS
ALTER COLUMN AGE INT NOT NULL;


  INSERT INTO CONSTRAINTTS
  VALUES('HA',9);
  SELECT * FROM CONSTRAINTTS
 

  --DEFAULT CONSTRAINT 

 CREATE TABLE CONSTRAINTTS1
  (
  EID CHAR(5) DEFAULT 'E0000',
 NAME CHAR(8),
 AGE INT
  )

  INSERT CONSTRAINTTS1
  VALUES('E0001','YASH',75);

  INSERT CONSTRAINTTS1(NAME,AGE)
  VALUES('YASH',75);
  SELECT * FROM CONSTRAINTTS1

  --IF TABLE IS ALREADY CREATED 
  ALTER TABLE CONSTRAINTTS1
  ADD CONSTRAINT R1 DEFAULT 'NF' FOR NAME
  SELECT * FROM CONSTRAINTTS1

  INSERT INTO CONSTRAINTTS1(AGE,EID)
  VALUES(80,'E0003')


  --UNIQUE CONSTRAINT (NO DUPLICATE)

  SELECT * FROM CONSTRAINTTS1
   
   ALTER TABLE CONSTRAINTTS1
   ADD CONSTRAINT R2 UNIQUE(NAME);
    -- DUPLICATE VALUE PRESENT LETS UPDATE IT
   UPDATE CONSTRAINTTS1 SET NAME='WKWK'
   WHERE EID='E0001';

   ALTER TABLE CONSTRAINTTS1
   ADD CONSTRAINT R2 UNIQUE(NAME);

   -- CHECK ( CHECKS THE CONDITION BEFORE LETTING THE VALUES IN )

   CREATE TABLE CHECKK
   (
   NAME CHAR(6),
   DOB DATE CHECK(DOB<'01-JAN-2000')
   );

   INSERT INTO CHECKK
   VALUES('ONEN','1-MAR-1990'); -- CONDITION MET

    INSERT INTO CHECKK
   VALUES('ONEN','1-MAR-2000'); -- CONDITION NOT MET 

   ALTER TABLE CHECKK
   ADD AGE INT;

   ALTER TABLE CHECKK
   ADD CONSTRAINT CKDB CHECK(AGE>18)

   SELECT * FROM CHECKK
   INSERT INTO CHECKK(NAME,DOB,AGE)
   VALUES('MEMOW','2-OCT-1999',19)

   --PRIMARY  KEY

   CREATE TABLE PRIMARYY
   (EID CHAR(3)PRIMARY KEY ,
   NAME CHAR(8),
   AGE INT
   );

   INSERT INTO PRIMARYY
   VALUES('E01','JOHHN',78)
   -- INSERT INTO PRIMARYY VALUES('E01','CINAA',98)  WONT WORK BCZ OF PRIMARY KEY
    INSERT INTO PRIMARYY
   VALUES('E02','RANYO',78)
   INSERT INTO PRIMARYY(NAME,AGE)
   VALUES('RANYO',78)

   ALTER TABLE PRIMARYY
   ADD CONSTRAINT PRMK PRIMARY KEY (EID)

   SELECT * FROM PRIMARYY


-- FOREIGN KEY  (LINKS ONE TABLE TO ANOTHER )

CREATE TABLE FOREIGNN
(
EID CHAR(3) REFERENCES PRIMARYY(EID), 
MALE_0R_FEMALE VARCHAR(6) 
)

