-- JOIN IN SQL 


CREATE DATABASE JOINN;

USE JOINN;

select * from EMP
select * from EMP_SAL

----WAY 1

SELECT EMP.NAME,EMP.CITY,EMP_SAL.SALARY FROM EMP
INNER JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID


-- WAY 2 USING ALIAS  AS THIS IS SUPER REQUIRED FOR MORE NUMBER OF TABLES

SELECT E1.NAME,E1.CITY,E2.SALARY 
FROM EMP E1
INNER JOIN EMP_SAL E2
ON E1.EID=E2.EID

-- WAY 3  SQL SERVER IS SMART ENOUGH TO RECOGNISE WHICH COLUMN BELONGS TO WHICH TABLE ONLY OCCURING COLUMN IN TABLE HAS TO BE SPECIFIED

SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
INNER JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID


-- LEFT AND RIGHT JOIN 


SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
LEFT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID


SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
RIGHT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID

--FULL JOIN 

SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
FULL  JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID

-- CROSS JOIN (NO. OF ROWS IN TABLE 1 * NO. OF ROWS IN SECOND TABLE)

SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
CROSS JOIN EMP_SAL

-- WHERE CLAUSE IF  INCLUDED WITH CROSS JOIN IT WILL BECOME INNER JOIN

-- SELF JOIN (JOINING WITHIN THE TABLE  ALIAS IS MOST REQUIRED)

CREATE TABLE Employees (
Id INT PRIMARY KEY,
FullName VARCHAR(50),
Salary DECIMAL(10, 2),
ManagerId INT
);

INSERT INTO Employees (Id, FullName, Salary, ManagerId)
VALUES
(1, 'John Smith', 10000, 3),
(2, 'Jane Anderson', 12000, 3),
(3, 'Tom Lanon', 15000, 4),
(4, 'Anne Connor', 20000, NULL),
(5, 'Jeremy York', 9000, 1);

SELECT *FROM Employees
SELECT *FROM Employees

-- SELF JOIN , I NEED THE NAMES OF THE MANAGER ACCORDING TO FULL NAME 

SELECT EMP.Id,EMP.FullName,manager.FullName
from	Employees EMP
JOIN Employees manager
on EMP.ManagerId=manager.Id


------------------------------------------------------------------------------------------------------------------
-- union  (combines two select statement)


SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
RIGHT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID
union
SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
LEFT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID

-- union all for duplicate values to be included

SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
RIGHT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID
union all
SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
LEFT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID

-- INTERSECTION (COMBINES TWO SELECT STATEMENT AND RETURNS ONLY COMMON RECORDS BETWEEN THEM)

SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
RIGHT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID
INTERSECT
SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
LEFT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID


----- EXCEPT CLAUSE (COMBINES TWO SELECT STATEMENT AND RETURNS THE VALUE THAT IS NOT PRESENT IN STATEMENT 2)


SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
LEFT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID
EXCEPT
SELECT EMP.EID, NAME , CITY ,DOJ,DEPT,DESI,SALARY
FROM EMP 
RIGHT JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID




