CREATE DATABASE OPERATOR;

USE OPERATOR

---OPERATORS IN SQL

SELECT*FROM EMP_SAL

SELECT 5.0/2,4%2,5%1,5%3, 5/2, 5*2, 5/2.0,   5.0*2 , 2*4.0

--COMPARISION OPT

SELECT * FROM EMP_SAL

SELECT * FROM EMP_SAL
WHERE SALARY=480000;

SELECT * FROM EMP_SAL
WHERE DEPT='HR'

SELECT * FROM EMP_SAL
WHERE SALARY!>50000
--LOGICAL OPT

SELECT * FROM EMP_SAL
WHERE SALARY>50000 AND DEPT='HR'

SELECT * FROM EMP_SAL
WHERE SALARY>50000 OR DEPT='HR'

--OTHER OPT
--BETWEEN

SELECT * FROM EMP_SAL
WHERE SALARY BETWEEN 50000 AND 800000;

--IN
                  
SELECT * FROM EMP_SAL
WHERE DEPT='HR'OR DEPT='OPS' OR DEPT='ADMIN'   --NORMAL TECH


SELECT * FROM EMP_SAL
WHERE DEPT IN ('HR','OPS','ADMIN') --USING IN

--IS NULL ( TO CHECK ANY NULL VALUES PRESENT IN THE COLUMN)


SELECT * FROM EMP_SAL WHERE SALARY IS NULL;


--DISTINCT OPERATOR 
SELECT DISTINCT DEPT FROM EMP_SAL;

-- COUNT CLAUSE   ( COUNTS THE TOTAL NUM OF RECORDS NO NULL VSLUES IF SPECIFIC COLUMN)

SELECT COUNT(*) FROM EMP_SAL; -- FOR ALL

SELECT COUNT(SALARY) FROM EMP_SAL;

-- DISTINCT CLAUSE 

SELECT DISTINCT(DEPT) FROM EMP_SAL 

SELECT COUNT(DISTINCT DEPT) FROM EMP_SAL -- TO COUNT  


-- GROUP BY 
 SELECT DESI , SUM(SALARY) AS 'TOTAL SALARY - DESIGNATION' FROM EMP_SAL
 GROUP BY DESI;  -- WILL COMBINE ALL THE MATCHING DESIGNATION SUM THE TOTAL SALAERY 

 SELECT DEPT , SUM(SALARY) AS 'TOTAL SALARY' FROM EMP_SAL
 GROUP BY DEPT;

 -- HAVING CLAUSE ( SIMILAR LIKE WHERE BUT THIS FILTERS OUT AGGRIGATE (CREATED COLUM) EX SUM(SALARY))
 SELECT DEPT , SUM(SALARY) AS 'TOTAL SALARY' FROM EMP_SAL
 GROUP BY DEPT
 HAVING SUM(SALARY)>100000 -- HERE

 -- ORDER BY (SORTING) DEFAULT ASCENDING

 SELECT SALARY FROM EMP_SAL
 ORDER BY SALARY DESC;


  SELECT* FROM EMP_SAL
 ORDER BY SALARY ; -- DEFAULT ASC


--QUESTION ; DEPT WISE MANAGER LIST WITH  NUMBER OF EMP , TOTAL SALARY  WHERE DESIG IS ,MANAGER AND TOTAL SAL SHOULD BE > 250000 AND OUTPUT IN DESCENDING


