---- STORED PROCEDURE 2

--Q INSERT THE VALUES INTO EMP DATASET THENN INSERT VALUES INTO EMP_SAL DATASET THEN CREATE TWO NEW COLUMN WHEN ISERTING INTO EMP _SAL DATASET HRA AND PF  ONCE DONE JOIN BOTH THE TABLE TOGETHER

USE ASSIGNMENT_5

SELECT *FROM EMP
SELECT *FROM EMP_SAL

-- SOLUTION


CREATE PROCEDURE INSJOIN @I AS INT,@N AS VARCHAR(30),@A1 AS VARCHAR(30),@A2 AS VARCHAR(30),@C AS VARCHAR(20),@PH AS VARCHAR(20),@EM AS VARCHAR(40),@DOB AS DATE,@DOJ AS DATE,@DPT AS VARCHAR(25), @DESI AS VARCHAR(30),@SAL AS INT
 AS 
 BEGIN
 INSERT INTO EMP VALUES(@I,@N,@A1,@A2,@C,@PH,@EM,@DOB,@DOJ)
 INSERT INTO EMP_SAL VALUES (@I,@DPT,@DESI,@SAL)

 SELECT*FROM EMP WHERE EID=@I
 SELECT *FROM EMP_SAL WHERE EID=@I

 SELECT EMP.EID,NAME,CITY,DOJ,DEPT,DESI,salary as 'baisc', EMP_SAL.salary*0.15 as 'hra',EMP_SAL.salary*0.09 as 'pf' from EMP
 inner join EMP_SAL ON EMP.EID=EMP_SAL.EID  
 WHERE EMP.EID=@I
 END;

 INSJOIN 1000,'RSH GUPTA','	SECTOR 7','	Rohini'	,'DELHI','9999002727','RK@YAHOO.CO.IN','1990-09-01','2012-03-15','ATM','MMRSCIENTIST',95000;




























