------------ STORED PROCEDURE-----------


-- IS A CONTAINER THAT STORES THE CODE FOR REUSABLITY 

USE ASSIGNMENT_6

CREATE PROCEDURE STORE1
AS
BEGIN
SELECT*FROM EMP WHERE CITY='DELHI'
END;

EXEC STORE1
EXECUTE STORE1

CREATE PROCEDURE STORE2 @A AS VARCHAR(20)
AS 
BEGIN 
SELECT * FROM EMP WHERE CITY=@A
END;

DROP PROCEDURE STORE2

EXEC STORE2 'DELHI'

----------  CREATING INSERT INTO FOR STAKEHOLDERS/ USERS TO INSERT DATA INTOP TABLE



CREATE PROCEDURE INSERTINTO @I AS INT,@N AS VARCHAR(30),@A1 AS VARCHAR(30),@A2 AS VARCHAR(30),@CITY AS VARCHAR(20),@PH AS VARCHAR(12),@EM AS VARCHAR(30),@DOB AS DATE,@DOJ AS DATE
AS 
BEGIN
INSERT INTO EMP
VALUES(@I,@N,@A1,@A2,@CITY,@PH,@EM,@DOB,@DOJ)

SELECT * FROM EMP WHERE EID =@I
END;
DROP PROCEDURE INSERTINTO

INSERTINTO 1900,'WAKAWAKA','JAIHDHAIH','JAJAJA','DUMBAI','922922922','RUTU@NU.COM','12-JUNE-1990','15-FEB-2001';










